from methods import *

assert(swap(30,40)==(40,30))
assert(check(9).lower()==('positive number').lower())
assert(checkDivisor(20,4)==[4,8,12,16,20])
assert(Divide(40,5)==(8,0))
assert(oddNumbers(15)==[1,3,5,7,9,11,13,15])
assert(sumOfDegits(143)==8)
assert(findSmallestDivisor(35)==5)
assert(sumOfSeries(1,3)==123)
assert(reverse(143)==341)
assert(average([1,3,5,7,9])==5)
assert(count(12345)==5)
assert(palindrome(1234321)==True)
assert(ifSubStringFound("I'm Sushruth student of BDA.","Sushruth")==3)
assert(indexSubStringFound("Sushruth is studying ME in BDA","Sushruth")==7)
assert(checkForCharacters("ME")==True)
assert(replace("Aaron")=="$n$ny$$ $n$")
assert(countVowels("ndfhoinfbhfcjbzisuabs")==10)
assert(replaceBlankSpace("My name is  Sushruth")=="My-name-is--Sushruth")
assert(findLength("sushruth")==8)
assert(findLargerString("sushruth","sushruth e s")=="Sushruth E S")
assert(countOfUpperLower("Sushruth E S")==(3,6))
assert(countCharsDigits("Sushruthes004")==(9,3))
assert(fullPattern("Sushruth did bachelors in BDA","Nidhi S Rao")==True)
assert(cumulative_Sum([1,2,4,5,7])==[1,3,7,12,19])
print(tenRandomNumbers())
print(tenRandomNumbersRange())
print(uniqueRandomNumbers())
print(randomNumbers())